Moved to lein 2 and fixed packaging/compiling issues.
Theoretically should be easy to compile and package the stuff with lein
2 now.

diff --git a/src/tokyocabinet/configure.in b/src/tokyocabinet/configure.in
--- a/src/tokyocabinet/configure.in
+++ b/src/tokyocabinet/configure.in
@@ -1,4 +1,4 @@
-# Source of configuration for Tokyo Cabinet
+# Source of configuration for Tokyo Cabinet for Java
 
 
 
@@ -7,319 +7,165 @@
 #================================================================
 
 # Package name
-AC_INIT(tokyocabinet, 1.4.47)
+AC_INIT(tokyocabinet-java, 1.24)
 
 # Package information
-MYLIBVER=9
-MYLIBREV=10
-MYFORMATVER="1.0"
+MYLIBVER=1
+MYLIBREV=1
 
 # Targets
-MYHEADERFILES="tcutil.h tchdb.h tcbdb.h tcfdb.h tctdb.h tcadb.h"
-MYLIBRARYFILES="libtokyocabinet.a"
-MYLIBOBJFILES="tcutil.o tchdb.o tcbdb.o tcfdb.o tctdb.o tcadb.o myconf.o md5.o"
-MYCOMMANDFILES="tcutest tcumttest tcucodec tchtest tchmttest tchmgr"
-MYCOMMANDFILES="$MYCOMMANDFILES tcbtest tcbmttest tcbmgr tcftest tcfmttest tcfmgr"
-MYCOMMANDFILES="$MYCOMMANDFILES tcttest tctmttest tctmgr tcatest tcamttest tcamgr"
-MYCGIFILES="tcawmgr.cgi"
-MYMAN1FILES="tcutest.1 tcumttest.1 tcucodec.1 tchtest.1 tchmttest.1 tchmgr.1"
-MYMAN1FILES="$MYMAN1FILES tcbtest.1 tcbmttest.1 tcbmgr.1 tcftest.1 tcfmttest.1 tcfmgr.1"
-MYMAN1FILES="$MYMAN1FILES tcttest.1 tctmttest.1 tctmgr.1 tcatest.1 tcamttest.1 tcamgr.1"
-MYMAN3FILES="tokyocabinet.3 tcutil.3 tcxstr.3 tclist.3 tcmap.3 tctree.3 tcmdb.3 tcmpool.3"
-MYMAN3FILES="$MYMAN3FILES tchdb.3 tcbdb.3 tcfdb.3 tctdb.3 tcadb.3"
-MYDOCUMENTFILES="COPYING ChangeLog doc tokyocabinet.idl"
-MYPCFILES="tokyocabinet.pc"
+MYJARFILES="tokyocabinet.jar"
+MYJAVAFILES="DBM.java HDB.java BDB.java BDBCUR.java BDBCMP.java FDB.java"
+MYJAVAFILES="$MYJAVAFILES TDB.java TDBQRY.java TDBQRYPROC.java ADB.java"
+MYJAVAFILES="$MYJAVAFILES HDBTest.java BDBTest.java FDBTest.java TDBTest.java ADBTest.java"
+MYJAVAFILES="$MYJAVAFILES Util.java Loader.java"
+MYLIBRARYFILES=""
+MYLIBOBJFILES="hdb.o bdb.o bdbcur.o fdb.o tdb.o tdbqry.o adb.o util.o myconf.o"
 
 # Building flags
 MYCFLAGS="-std=c99 -Wall -fPIC -fsigned-char -O2"
-MYCPPFLAGS="-I. -I\$(INCLUDEDIR) -I$HOME/include -I/usr/local/include"
-MYCPPFLAGS="$MYCPPFLAGS -DNDEBUG -D_GNU_SOURCE=1 -D_REENTRANT -D__EXTENSIONS__"
+MYCPPFLAGS="-I. -I\$(INCLUDEDIR) -L$HOME/include -L/usr/local/include -DNDEBUG -D_GNU_SOURCE=1"
 MYLDFLAGS="-L. -L\$(LIBDIR) -L$HOME/lib -L/usr/local/lib"
-MYCMDLDFLAGS=""
 MYRUNPATH="\$(LIBDIR)"
 MYLDLIBPATHENV="LD_LIBRARY_PATH"
-MYPOSTCMD="true"
 
 # Building paths
-PATH="$PATH:$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
-PATH="$PATH:/opt/SUNWspro/bin:/usr/ccs/bin:/usr/xpg4/bin:/usr/xpg6/bin:/usr/ucb"
-CPATH="$HOME/include:/usr/local/include:$CPATH"
+pathtmp="$PATH"
+PATH="$HOME/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"
+PATH="$PATH:/usr/ccs/bin:/usr/ucb:/usr/xpg4/bin:/usr/xpg6/bin:$pathtmp"
 LIBRARY_PATH="$HOME/lib:/usr/local/lib:$LIBRARY_PATH"
 LD_LIBRARY_PATH="$HOME/lib:/usr/local/lib:$LD_LIBRARY_PATH"
+CPATH="$HOME/include:/usr/local/include:$CPATH"
 PKG_CONFIG_PATH="$HOME/lib/pkgconfig:/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
-export PATH CPATH LIBRARY_PATH LD_LIBRARY_PATH PKG_CONFIG_PATH
-
-
-
-#================================================================
-# Options
-#================================================================
-
-
-# Internal variables
-enables=""
-
-# Debug mode
-AC_ARG_ENABLE(debug,
-  AC_HELP_STRING([--enable-debug], [build for debugging]))
-if test "$enable_debug" = "yes"
+export PATH LIBRARY_PATH LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH
+if type pkg-config > /dev/null 2>&1
 then
-  MYCFLAGS="-std=c99 -Wall -fPIC -pedantic -fsigned-char -g -O0"
-  MYCPPFLAGS="$MYCPPFLAGS -UNDEBUG"
-  MYCMDLDFLAGS="$MYCMDLDFLAGS -static"
-  enables="$enables (debug)"
-fi
-
-# Developping mode
-AC_ARG_ENABLE(devel,
-  AC_HELP_STRING([--enable-devel], [build for development]))
-if test "$enable_devel" = "yes"
-then
-  MYCFLAGS="-std=c99 -Wall -fPIC -pedantic -fsigned-char -g -O2 -pipe"
-  MYCPPFLAGS="$MYCPPFLAGS -UNDEBUG"
-  enables="$enables (devel)"
-fi
-
-# Profiling mode
-AC_ARG_ENABLE(profile,
-  AC_HELP_STRING([--enable-profile], [build for profiling]))
-if test "$enable_profile" = "yes"
-then
-  MYCFLAGS="-std=c99 -Wall -fPIC -pedantic -fsigned-char -g -pg -O2 -pipe"
-  enables="$enables (profile)"
-fi
-
-# Static mode
-AC_ARG_ENABLE(static,
-  AC_HELP_STRING([--enable-static], [build by static linking]))
-if test "$enable_static" = "yes"
-then
-  MYCMDLDFLAGS="$MYCMDLDFLAGS -static"
-  enables="$enables (static)"
-fi
-
-# Fastest mode
-AC_ARG_ENABLE(fastest,
-  AC_HELP_STRING([--enable-fastest], [build for fastest run]))
-if test "$enable_fastest" = "yes"
-then
-  MYLIBOBJFILES="tokyocabinet_all.o"
-  MYCFLAGS="-std=c99 -Wall -fPIC -pedantic -fsigned-char -O3"
-  MYCFLAGS="$MYCFLAGS -fomit-frame-pointer -fforce-addr -minline-all-stringops"
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYFASTEST"
-  enables="$enables (fastest)"
-fi
-
-# 64-bit offset mode
-AC_ARG_ENABLE(off64,
-  AC_HELP_STRING([--enable-off64], [build with 64-bit file offset on 32-bit system]))
-if test "$enable_off64" = "yes"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_FILE_OFFSET_BITS=64"
-  enables="$enables (off64)"
-fi
-
-# Swapping byte-orders mode
-AC_ARG_ENABLE(swab,
-  AC_HELP_STRING([--enable-swab], [build for swapping byte-orders]))
-if test "$enable_swab" = "yes"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYSWAB"
-  enables="$enables (swab)"
-fi
-
-# Micro yield mode
-AC_ARG_ENABLE(uyield,
-  AC_HELP_STRING([--enable-uyield], [build for detecting race conditions]))
-if test "$enable_uyield" = "yes"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYMICROYIELD"
-  enables="$enables (uyield)"
-fi
-
-# Disable the unified buffer cache assumption
-AC_ARG_ENABLE(ubc,
-  AC_HELP_STRING([--disable-ubc], [build without the unified buffer cache assumption]))
-if test "$enable_ubc" = "no"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYNOUBC"
-  enables="$enables (no-ubc)"
-fi
-
-# Disable ZLIB compression
-AC_ARG_ENABLE(zlib,
-  AC_HELP_STRING([--disable-zlib], [build without ZLIB compression]))
-if test "$enable_zlib" = "no"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYNOZLIB"
-  enables="$enables (no-zlib)"
-fi
-
-# Disable BZIP2 compression
-AC_ARG_ENABLE(bzip,
-  AC_HELP_STRING([--disable-bzip], [build without BZIP2 compression]))
-if test "$enable_bzip" = "no"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYNOBZIP"
-  enables="$enables (no-bzip)"
-fi
-
-# Disable POSIX thread
-AC_ARG_ENABLE(pthread,
-  AC_HELP_STRING([--disable-pthread], [build without POSIX thread support]))
-if test "$enable_pthread" = "no"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYNOPTHREAD"
-  enables="$enables (no-pthread)"
-fi
-
-# Disable shared object
-AC_ARG_ENABLE(shared,
-  AC_HELP_STRING([--disable-shared], [avoid to build shared libraries]))
-if test "$enable_shared" = "no"
-then
-  enables="$enables (no-shared)"
-fi
-
-# Enable custom codec functions of LZMA
-AC_ARG_ENABLE(exlzma,
-  AC_HELP_STRING([--disable-exlzma], [build with the custom codec of LZMA]))
-if test "$enable_exlzma" = "yes"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYEXLZMA"
-  enables="$enables (exlzma)"
-fi
-
-# Enable custom codec functions of LZO
-AC_ARG_ENABLE(exlzo,
-  AC_HELP_STRING([--disable-exlzo], [build with the custom codec of LZO]))
-if test "$enable_exlzo" = "yes"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -D_MYEXLZO"
-  enables="$enables (exlzo)"
-fi
-
-# Specify the installation path of ZLIB
-AC_ARG_WITH(zlib,
-  AC_HELP_STRING([--with-zlib=DIR], [search DIR/include and DIR/lib for ZLIB]))
-if test -n "$with_zlib"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -I$with_zlib/include"
-  MYLDFLAGS="$MYLDFLAGS -L$with_zlib/lib"
-  MYRUNPATH="$MYRUNPATH:$with_zlib/lib"
-  CPATH="$CPATH:$with_zlib/include"
-  LIBRARY_PATH="$LIBRARY_PATH:$with_zlib/lib"
-  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$with_zlib/lib"
-fi
-
-# Specify the installation path of BZIP2
-AC_ARG_WITH(bzip,
-  AC_HELP_STRING([--with-bzip=DIR], [search DIR/include and DIR/lib for BZIP2]))
-if test -n "$with_bzip"
-then
-  MYCPPFLAGS="$MYCPPFLAGS -I$with_bzip/include"
-  MYLDFLAGS="$MYLDFLAGS -L$with_bzip/lib"
-  MYRUNPATH="$MYRUNPATH:$with_bzip/lib"
-  CPATH="$CPATH:$with_bzip/include"
-  LIBRARY_PATH="$LIBRARY_PATH:$with_bzip/lib"
-  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$with_bzip/lib"
+  PATH="$PATH:`pkg-config --variable=bindir tokyocabinet`"
+  LIBRARY_PATH="$LIBRARY_PATH:`pkg-config --variable=libdir tokyocabinet`"
+  LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pkg-config --variable=libdir tokyocabinet`"
+  CPATH="$CPATH:`pkg-config --variable=includedir tokyocabinet`"
+  export PATH LIBRARY_PATH LD_LIBRARY_PATH CPATH PKG_CONFIG_PATH
 fi
 
 # Messages
 printf '#================================================================\n'
-printf '# Configuring Tokyo Cabinet version %s%s.\n' "$PACKAGE_VERSION" "$enables"
+printf '# Configuring Tokyo Cabinet for Java version %s.\n' "$PACKAGE_VERSION"
 printf '#================================================================\n'
 
 
 
 #================================================================
-# Checking Commands and Libraries
+# Checking Commands to Build with
 #================================================================
+
+# Home directory of Java
+printf 'checking MYJAVAHOME... '
+if test -d "$JAVA_HOME"
+then
+  MYJAVAHOME="$JAVA_HOME"
+fi
+printf '%s\n' "$MYJAVAHOME"
+
+# Platform of Java
+printf 'checking JVMPLATFORM... '
+if uname | grep Darwin > /dev/null
+then
+  JVMPLATFORM="mac"
+else
+  for file in `\ls $MYJAVAHOME/include`
+  do
+    if test -d "$MYJAVAHOME/include/$file"
+    then
+      JVMPLATFORM="$file"
+    fi
+  done
+fi
+printf '%s\n' "$JVMPLATFORM"
+MYCPPFLAGS="$MYCPPFLAGS -I$MYJAVAHOME/include -I$MYJAVAHOME/include/$JVMPLATFORM"
+CPATH="$CPATH:$MYJAVAHOME/include:$MYJAVAHOME/include/$JVMPLATFORM"
+
+# Java compiler
+printf 'checking JAVAC... '
+JAVAC="$MYJAVAHOME/bin/javac"
+if uname | grep Darwin > /dev/null
+then
+  if test -x "$MYJAVAHOME/Commands/javac"
+  then
+    JAVAC="$MYJAVAHOME/Commands/javac"
+  else
+    JAVAC="$MYJAVAHOME/bin/javac"
+  fi
+fi
+if test -x "$JAVAC"
+then
+  printf '%s\n' "$JAVAC"
+else
+  printf 'no\n'
+  printf '#================================================================\n' 1>&2
+  printf '# WARNING: %s is not found.\n' "$JAVAC" 1>&2
+  printf '#================================================================\n' 1>&2
+fi
+JAVACFLAGS="-source 1.5 -d ."
+
+# Other building tools
+if uname | grep Darwin > /dev/null
+then
+  if test -x "$MYJAVAHOME/Commands/java"
+  then
+    JAR="$MYJAVAHOME/Commands/jar"
+    JAVAH="$MYJAVAHOME/Commands/javah"
+    JAVADOC="$MYJAVAHOME/Commands/javadoc"
+    JAVARUN="$MYJAVAHOME/Commands/java"
+  else
+    JAR="$MYJAVAHOME/bin/jar"
+    JAVAH="$MYJAVAHOME/bin/javah"
+    JAVADOC="$MYJAVAHOME/bin/javadoc"
+    JAVARUN="$MYJAVAHOME/bin/java"
+  fi
+else
+  JAR="$MYJAVAHOME/bin/jar"
+  JAVAH="$MYJAVAHOME/bin/javah"
+  JAVADOC="$MYJAVAHOME/bin/javadoc"
+  JAVARUN="$MYJAVAHOME/bin/java"
+fi
 
 # C compiler
 AC_PROG_CC
 
-# Reset variables
-if test "$GCC" != "yes"
-then
-  AC_MSG_WARN([another compiler except for GCC was detected])
-  MYCFLAGS=""
-fi
-test -n "$CFLAGS" && MYCFLAGS="$CFLAGS $MYCFLAGS"
-test -n "$CPPFLAGS" && MYCPPFLAGS="$CPPFLAGS $MYCPPFLAGS"
-test -n "$LDFLAGS" && MYLDFLAGS="$LDFLAGS $MYLDFLAGS"
-
-# Byte order
-AC_C_BIGENDIAN(MYCPPFLAGS="$MYCPPFLAGS -D_MYBIGEND")
-
 # Underlying libraries
 AC_CHECK_LIB(c, main)
 AC_CHECK_LIB(m, main)
-if test "$enable_pthread" != "no"
-then
-  AC_CHECK_LIB(pthread, main)
-  AC_CHECK_LIB(rt, main)
-fi
-if test "$enable_zlib" != "no"
-then
-  AC_CHECK_LIB(z, main)
-fi
-if test "$enable_bzip" != "no"
-then
-  AC_CHECK_LIB(bz2, main)
-fi
-if test "$enable_exlzma" = "yes"
-then
-  AC_CHECK_LIB(lzma, main)
-fi
-if test "$enable_exlzo" = "yes"
-then
-  AC_CHECK_LIB(lzo2, main)
-fi
-AC_CHECK_LIB(tokyocabinet, main, AC_MSG_WARN([old version of Tokyo Cabinet was detected]))
+AC_CHECK_LIB(pthread, main)
+AC_CHECK_LIB(z, main)
+AC_CHECK_LIB(bz2, main)
+AC_CHECK_LIB(tokyocabinet, main)
 
 # Necessary headers
 AC_CHECK_HEADER(stdlib.h, true, AC_MSG_ERROR([stdlib.h is required]))
 AC_CHECK_HEADER(stdint.h, true, AC_MSG_ERROR([stdint.h is required]))
-AC_CHECK_HEADER(unistd.h, true, AC_MSG_ERROR([unistd.h is required]))
-AC_CHECK_HEADER(dirent.h, true, AC_MSG_ERROR([dirent.h is required]))
-AC_CHECK_HEADER(regex.h, true, AC_MSG_ERROR([regex.h is required]))
-AC_CHECK_HEADER(glob.h, true, AC_MSG_ERROR([glob.h is required]))
-if test "$enable_pthread" != "no"
+AC_CHECK_HEADER(tcutil.h, true, AC_MSG_ERROR([tcutil.h is required]))
+AC_CHECK_HEADER(jni.h, true, AC_MSG_ERROR([jni.h is required]))
+
+# Checking the version of Tokyo Cabinet with pkg-config
+if type pkg-config > /dev/null 2>&1 && pkg-config --atleast-version=1.0.3 tokyocabinet
 then
-  AC_CHECK_HEADER(pthread.h, true, AC_MSG_ERROR([pthread.h is required]))
-fi
-if test "$enable_zlib" != "no"
-then
-  AC_CHECK_HEADER(zlib.h, true, AC_MSG_ERROR([zlib.h is required]))
-fi
-if test "$enable_bzip" != "no"
-then
-  AC_CHECK_HEADER(bzlib.h, true, AC_MSG_ERROR([bzlib.h is required]))
-fi
-if test "$enable_exlzma" = "yes"
-then
-  AC_CHECK_HEADER(lzmalib.h, true, AC_MSG_ERROR([lzmalib.h is required]))
-fi
-if test "$enable_exlzo" = "yes"
-then
-  AC_CHECK_HEADER(lzo/lzo1x.h, true, AC_MSG_ERROR([lzo/lzo1x.h is required]))
+  MYCPPOPTS="$MYCPPOPTS -I`pkg-config --variable=includedir tokyocabinet`"
+  MYLDOPTS="$MYLDOPTS -L`pkg-config --variable=libdir tokyocabinet`"
+  MYRUNPATH="$MYRUNPATH:`pkg-config --variable=libdir tokyocabinet`"
 fi
 
 # Shared libraries
-if test "$enable_shared" != "no" && test "$enable_profile" != "yes"
+if uname | grep Darwin >/dev/null
 then
-  if uname | grep Darwin >/dev/null
-  then
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.$MYLIBVER.$MYLIBREV.0.dylib"
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.$MYLIBVER.dylib"
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.dylib"
-    MYLDLIBPATHENV="DYLD_LIBRARY_PATH"
-  else
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.so.$MYLIBVER.$MYLIBREV.0"
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.so.$MYLIBVER"
-    MYLIBRARYFILES="$MYLIBRARYFILES libtokyocabinet.so"
-  fi
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.$MYLIBVER.$MYLIBREV.0.dylib"
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.$MYLIBVER.dylib"
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.dylib"
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.jnilib"
+  MYLDLIBPATHENV="DYLD_LIBRARY_PATH"
+else
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.so.$MYLIBVER.$MYLIBREV.0"
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.so.$MYLIBVER"
+  MYLIBRARYFILES="$MYLIBRARYFILES libjtokyocabinet.so"
 fi
 
 
@@ -328,29 +174,29 @@ fi
 # Generic Settings
 #================================================================
 
+
 # Export variables
 AC_SUBST(MYLIBVER)
 AC_SUBST(MYLIBREV)
-AC_SUBST(MYFORMATVER)
-AC_SUBST(MYHEADERFILES)
+AC_SUBST(MYJARFILES)
+AC_SUBST(MYJAVAFILES)
 AC_SUBST(MYLIBRARYFILES)
 AC_SUBST(MYLIBOBJFILES)
-AC_SUBST(MYCOMMANDFILES)
-AC_SUBST(MYCGIFILES)
-AC_SUBST(MYMAN1FILES)
-AC_SUBST(MYMAN3FILES)
-AC_SUBST(MYDOCUMENTFILES)
-AC_SUBST(MYPCFILES)
+AC_SUBST(MYJAVAHOME)
+AC_SUBST(JAVAC)
+AC_SUBST(JAVACFLAGS)
+AC_SUBST(JAR)
+AC_SUBST(JAVAH)
+AC_SUBST(JAVADOC)
+AC_SUBST(JAVARUN)
 AC_SUBST(MYCFLAGS)
 AC_SUBST(MYCPPFLAGS)
 AC_SUBST(MYLDFLAGS)
-AC_SUBST(MYCMDLDFLAGS)
 AC_SUBST(MYRUNPATH)
 AC_SUBST(MYLDLIBPATHENV)
-AC_SUBST(MYPOSTCMD)
 
 # Targets
-AC_OUTPUT(Makefile tokyocabinet.pc)
+AC_OUTPUT(Makefile)
 
 # Messages
 printf '#================================================================\n'
